name: Kimai
services:
  sqldb:
    image: mysql:8.3
    volumes:
      - /DATA/AppData/kimai/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changethis
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -uroot -p$$MYSQL_ROOT_PASSWORD ping -h 127.0.0.1 --silent
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
  kimai:
    image: kimai/kimai2:stable
    depends_on:
      sqldb:
        condition: service_healthy
        restart: true
    volumes:
      - /DATA/AppData/kimai/data:/opt/kimai/var/data
      - /DATA/AppData/kimai/plugins:/opt/kimai/var/plugins
    ports:
      - 8001:8001
    environment:
      - APP_SECRET=change-this-to-a-long-string
      - TRUSTED_HOSTS=kimai.domain.com
      - ADMINMAIL=kimai@domain.com
      - ADMINPASS=changethis
      - "DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0"
    restart: unless-stopped
x-casaos:
  id: org.mempii.kimai
  architectures:
    - amd64
    - arm64
  main: kimai
  author: mempii
  category: Productivity
  description:
    en_US: Time tracker.
  developer: Kimai
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/kimai.svg
  tips:
    before_install:
      en_US: |
        Change mysql root password, Kimai admin password, domain name and admin e-mail.
  title:
    en_US: Kimai
  port_map: "8001"
  update_at: "2026-07-18"
  repo: https://github.com/kimai/kimai
