name: affine

services:
  affine:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_server
    ports:
    - 3010:3010
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
    - /DATA/AppData/affine/storage:/root/.affine/storage
    - /DATA/AppData/affine/config:/root/.affine/config
    environment:
    - AFFINE_SERVER_EXTERNAL_URL=https://affine.yourdomain.com
    - DATABASE_URL=postgresql://affine:CHANGETHIS1@postgres:5432/affine

    - REDIS_SERVER_HOST=redis
    - AFFINE_INDEXER_ENABLED=false
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_migration_job
    volumes:
    - /DATA/AppData/affine/storage:/root/.affine/storage
    - /DATA/AppData/affine/config:/root/.affine/config
    command:
    - sh
    - -c
    - node ./scripts/self-host-predeploy.js
    environment:
    - DATABASE_URL=postgresql://affine:CHANGETHIS1@postgres:5432/affine

    - REDIS_SERVER_HOST=redis
    - AFFINE_INDEXER_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    container_name: affine_redis
    healthcheck:
      test:
      - CMD
      - redis-cli
      - --raw
      - incr
      - ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres
    volumes:
    - /DATA/AppData/affine/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: CHANGETHIS1
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: --data-checksums
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - affine
      - -d
      - affine
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

x-casaos:
  id: org.mempii.affine
  main: affine
  index: /
  port_map: '3010'
  scheme: http
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/affine-light.svg
  title:
    en_US: AFFiNE
  tagline:
    en_US: Self-hosted knowledge base for better collaboration
  description:
    en_US: |
      AFFiNE is a self-hosted knowledge base that allows you to create, edit, and collaborate on documents in real-time.
      It provides a modern, intuitive interface for managing knowledge and documentation.
  category: Productivity
  author: mempii
  developer: TOEVERYTHING
  version: "1.0.0"
  update_at: "2026-07-24"
  architectures:
    - amd64
    - arm64
  website: https://affine.pro
  repo: https://github.com/toeverything/AFFiNE
  tips:
    before_install:
      en_US: |
        Change postgres password (CHANGETHIS1) and AFFINE_SERVER_EXTERNAL_URL
